/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./DriverController.js";
export * from "./HelloWorldController.js";
export * from "./LocationController.js";
export * from "./UserController.js";
