/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./AnalyticsController.js";
export * from "./BookingController.js";
export * from "./ComprehensiveAnalyticsController.js";
export * from "./DriverController.js";
export * from "./HelloWorldController.js";
export * from "./HospitalController.js";
export * from "./LocationController.js";
export * from "./MonitoringController.js";
export * from "./UserController.js";
export * from "./VoiceBookingController.js";
